# Generated by Django 3.2 on 2021-05-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('1', 'NEW'), ('2', 'REFURBISHED'), ('3', 'USED')], default='1', max_length=1)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='#', verbose_name='pic')),
            ],
        ),
    ]
